# Generated by Django 3.2.2 on 2021-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag3',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='hasker.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
