# Generated by Django 3.2.2 on 2021-06-11 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hasker', '0004_auto_20210610_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voters',
            field=models.ManyToManyField(related_name='questions', through='hasker.QuestionVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
