# Generated by Django 3.2.2 on 2021-06-11 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hasker', '0005_question_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voters',
            field=models.ManyToManyField(related_name='answers', through='hasker.AnswerVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
